config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:update] do
    post "downgrade"
  end
  
  resources :charges, only: [:new, :create]

  resources :wikis do
    resources :collaborators
  end

  get 'about' => 'welcome#about'
  # get 'collaborators_edit' => 'collaborators#edit'
  # post 'collaborators_update' => 'collaborators#update'

  root to: 'wikis#index'

  
 
end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user
  
  def self.collaborators
    User.where(id: pluck(:user_id))
  end

  def self.wikis
    Wiki.where(id: pluck(:wiki_id))
  end

  def wiki
    Wiki.where(id: wiki_id)
  end

  def collaborator
    User.where(id: collaborator_id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :owned_wikis, class_name: 'Wiki', foreign_key: 'owner_id'
  has_many :collaborations, foreign_key: 'collaborator_id'
  has_many :collaborated_wikis, through: :collaborations, source: :wiki
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

   def admin?
     role == 'admin'
   end
   
   def moderator?
     role == 'moderator'
   end

  def owned_wikis
    Wiki.where(owner_id: id)
  end

  def collaborations
    Collaboration.where(collaborator_id: id)
  end

  def collaborated_wikis
    collaborations.wikis
  end
   
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  belongs_to :owner, class_name: 'User'
  has_many :collaborations
  has_many :collaborators, through: :collaborations, source: :collaborator

  def owner
    User.where(id: owner_id)
  end

  def collaborations
    Collaboration.where(wiki_id: id)
  end

  def collaborators
    collaborations.collect(&:user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit
   protect_from_forgery with: :exception
   before_action :configure_permitted_parameters, if: :devise_controller?

   rescue_from Pundit::NotAuthorizedError do |exception|
     redirect_to root_url, alert: exception.message
   end
 
   protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
   end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :authenticate_user!
  def new
    @stripe_btn_data = {
    key: "#{ Rails.configuration.stripe[:publishable_key] }",
    description: "Big Money Membership - #{current_user.name || current_user.email}",
    amount: 1500
    }
  end

  def create
    # Amount in cents
    @amount = 1500

    customer = Stripe::Customer.create(
      email: current_user.email,
      card:  params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer:  customer.id,
      amount:    @amount,
      description: "Big Money Membership - #{current_user.name || current_user.email}",
      currency: 'usd'
    )

    current_user.role = 'premium'
    current_user.save

    flash[:notice] = "Thanks for your BigTime membership, #{current_user.name || current_user.email}"
    redirect_to wikis_path

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController

  def create
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = Collaboration.new( user_id: collaborator_params[:user_id], wiki_id: params[:wiki_id] )
    if @collaborator.save
      flash[:notice] = "Collaborator was saved."
    else
      flash[:error] = "There was an error saving collaborator. Please try again."
    end

    redirect_to edit_wiki_path(@wiki)
  end

 
   def show
    @wiki = Wiki.find(params[:id])
    @users = User.all.reject { |u| u.id == current_user.id }
    @collaborators = @wiki.collaborators

    authorize @wiki
    # if request.path != wiki_path(@wiki)
    #   redirect_to @wiki, status: :moved_permanently
    # end
  end

  def destroy
    @wiki = Wiki.friendly.find(params[:wiki_id])
    @collaborator = @wiki.collaborators.find(params[:id])

    if @collaborator.destroy
      flash[:notice] = "Collaborator was removed from wiki."
    else
      flash[:error] = "There was an error removing collaborator. Please try again."
    end

    redirect_to edit_wiki_path(@wiki)
  end


  

  
  private

  def collaborator_params
    params.require(:collaboration).permit(:user_id, :wiki_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  # def index
  #   @wikis = Wiki.all
  #     authorize @wikis
  # end

  def index
    # puts "this is the#{current_user.role}"
    if user_signed_in? && current_user.role == 'premium'
      @private_wikis = Wiki.where("user_id = ? AND private = ?", current_user.id, true)
    end
    @public_wikis = Wiki.where("private = ?", false)
  end

  def show
    @wiki = Wiki.find(params[:id])
      authorize @wiki
    @users = User.all.reject { |u| u.id == current_user.id }
    @collaborators = @wiki.collaborators
  
    if request.path != wiki_path(@wiki)
      redirect_to @wiki, status: :moved_permanently
    end
  end

  def new
    @wiki = Wiki.new
      authorize @wiki
  end

  def edit
    @wiki = Wiki.find(params[:id])
      authorize @wiki
  end

  def create
    @wiki = Wiki.new(params.require(:wiki).permit(:title, :body, :private))
    @wiki.user = current_user
      authorize @wiki
    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def update
     @wiki = Wiki.find(params[:id])
      authorize @wiki
     if @wiki.update_attributes(params.require(:wiki).permit(:title, :body))
       flash[:notice] = "Wiki was updated."
       redirect_to @wiki
     else
       flash[:error] = "There was an error saving the post. Please try again."
       render :edit
     end
   end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown_to_html(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end
  
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span>Amount $<%= @stripe_btn_data[:amount].to_int/100 %> </span>
    </label>
  </article>

  <%= form_tag charges_path do %>
   <h4>Click the button!</h4>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" 
    data-key="<%= @stripe_btn_data[:key] %>" 
    data-amount=<%= @stripe_btn_data[:amount] %> 
    data-description="<%= @stripe_btn_data[:description] %>" ></script>
  <% end %>
<% end %>

app/views/collaborators/edit.html.erb
<h1>Collaborators#edit</h1>
<p>Find me in app/views/collaborators/edit.html.erb</p>

app/views/collaborators/index.html.erb
<h1>Collaborators#index</h1>
<p>Find me in app/views/collaborators/index.html.erb</p>

app/views/collaborators/new.html.erb
<%= form_for ([@wiki, @collaborator]) do |f| %>
  <% if @collaborator.errors.any? %>
    <div class="alert alert-danger">
      <h4>There are <%= pluralize(@collaborator.errors.count, "error") %>.</h4>
      <ul>
        <% @collaborator.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='row'>
    <div class='col-md-6'>
      <% if current_user.admin? || current_user.premium? && current_user == wiki.user %>
      <h3>Add Collaborators</h3>
      <table class="table table-striped">
      <tbody>
      <% users.each do |user| %>
        <%= form_for [wiki, collaborator] do |f| %>
          <tr>
            <td>
            <%= user.name %>
            <%= f.hidden_field :wiki_id, value: wiki.id %>
            <%= f.hidden_field :user_id, value: user.id %>
            </td>
            <% if wiki.users.include?(user) %>
              <% collaborator = Collaborator.where(user_id: user.id, wiki_id: wiki.id).first %>
              <td>
                <%= link_to "", [wiki, collaborator], method: :delete, data: { confirm: 'Are you sure you want to remove collaborator?'}, class: 'btn btn-danger btn glyphicon glyphicon-remove-sign bloc_right'%>  
              </td>
            <% else %>
              <td>
                <%= f.submit "+", class: 'btn btn-success btn plus bloc_right' %>
              </td>
            <% end %> 
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/collaborators/show.html.erb
<%= form_for ([@wiki, @collaborator]) do |f| %>
  <% if @collaborator.errors.any? %>
    <div class="alert alert-danger">
      <h4>There are <%= pluralize(@collaborator.errors.count, "error") %>.</h4>
      <ul>
        <% @collaborator.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='row'>
    <div class='col-md-6'>
      <% if current_user.admin? || current_user.premium? && current_user == wiki.user %>
      <h3>Add Collaborators</h3>
      <table class="table table-striped">
      <tbody>
      <% users.each do |user| %>
        <%= form_for [wiki, collaborator] do |f| %>
          <tr>
            <td>
            <%= user.name %>
            <%= f.hidden_field :wiki_id, value: wiki.id %>
            <%= f.hidden_field :user_id, value: user.id %>
            </td>
            <% if wiki.users.include?(user) %>
              <% collaborator = Collaborator.where(user_id: user.id, wiki_id: wiki.id).first %>
              <td>
                <%= link_to "", [wiki, collaborator], method: :delete, data: { confirm: 'Are you sure you want to remove collaborator?'}, class: 'btn btn-danger btn glyphicon glyphicon-remove-sign bloc_right'%>  
              </td>
            <% else %>
              <td>
                <%= f.submit "+", class: 'btn btn-success btn plus bloc_right' %>
              </td>
            <% end %> 
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <h1 class='text-uppercase'><%= link_to "Blocipedia", root_path %></h1>
    <ul class="nav nav-tabs">
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Wikis", wikis_path %></li>
      <li><%= link_to "Upgrade Account", new_charge_path %></li>
      <div class="pull-right user-info">
        <% if current_user %>
         Hello <%= link_to (current_user.name || current_user.email), edit_user_registration_path %>! <%= current_user.role %> Member <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %> or
            <%= link_to "Sign Up", new_user_registration_path %>
      <% end %>
      </div>
    </ul>
    <% if flash[:notice] %>
      <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/welcome/about.html.erb
<h1>About Blocipedia</h1>
<p>Another Alex Singleton production.</p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
  <h1>Blocipedia</h1>
  <p>Bloccit is a resource for sharing links with your friends!</p>
  <p>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
  </p>
</div>

<div class="row">
  <div class="col-md-4">
    <h2>Liberating</h2>
    <p>Blocipedia!</p>
  </div>
  <div class="col-md-4">
    <h2>Enlightening</h2>
    <p>Blocipedia!  </p>
  </div>
  <div class="col-md-4">
    <h2>Illuminating</h2>
    <p>Blocipedia! </p>
  </div>
</div>

app/views/wikis/_form.html.erb
<%= form_for wiki do |f| %>
      <% if wiki.errors.any? %>
        <div class="alert alert-danger">
          <h4>There are <%= pluralize(wiki.errors.count, "error") %>.</h4>
          <ul>
            <% @wiki.errors.full_messages.each do |msg| %>
             <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <div id="epiceditor" class="field"></div>
        <%= f.text_area :body, class: 'form-control hide', id: "epictextarea", placeholder: "Enter wiki body" %>
        
      </div>

      <% if current_user.role == 'admin' || current_user.role == 'premium' && current_user == wiki.user %>
        <div class="form-group">
          <%= f.label :private, class: 'checkbox private_check' do %>
          <%= f.check_box :private %> Private wiki
        </div>
          <% end %>
      <% end %>
      <div class="form-group">
        <%= f.submit "Submit Wiki", class: 'btn btn-success' %>
      </div>
    <% end %>

app/views/wikis/edit.html.erb
 <h1>Edit Wiki</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for wikis</p>
     <ul>
       <li>Make sure the it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @wiki do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
       </div>
          <% if current_user.role == 'admin' || current_user.role == 'premium' %>
          <div class="form-group">
            <%= f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private %> Private wiki
          </div>
            <% end %>
        <% end %>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/wikis/index.html.erb
<div class="jumbotron">
  <h1>Blocipedia</h1>
  <p>Create your own wikis!</p>
  <% if current_user == nil %>
  <p>
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> 
  </p>
  <% elsif current_user.role == 'standard'  %>
    <h3>Upgrade your account to create your own private wikis!</h3>
    <%= link_to "Upgrade", new_charge_path, id: 'upgrade', class: 'btn btn-primary' %>
  <% end %>
</div>
<div class="row">
  <div class="col-md-8">
    <% if user_signed_in? && current_user.role == 'premium' %>
      <h1>Private Wikis</h1>
      <ul class="list-group bloc-index">
        <% if @private_wikis.empty? %>
          <h4>You have no private wikis in your account. <%= link_to "Create a private wiki now.", new_wiki_path(@wiki)  %> </h4>
        <% else %>
          <% @private_wikis.each do |wiki| %>
             <li class="list-group-item"><%= link_to (markdown_to_html wiki.title), wiki %></li>
          <% end %>
        <% end %>
      </ul>
    <% end %>
    <h1>Public Wikis</h1>
    <ul class="list-group bloc-index">
      <% @public_wikis.each do |wiki| %>
        <li class="list-group-item"><%= link_to (markdown_to_html wiki.title), wiki %></li>
      <% end %>
    </ul>
    <% if policy(Wiki.new).create? %>
    <%= link_to " New", new_wiki_path(@wiki), class: 'btn btn-success glyphicon glyphicon-plus' %>
    <% end %>
  </div>
</div>

app/views/wikis/new.html.erb
 <h1>New Wiki</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for posts</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @wiki do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
       </div>
       <% if current_user.role == 'admin' || current_user.role == 'premium' %>
        <div class="form-group">
          <%= f.label :private, class: 'checkbox private_check' do %>
          <%= f.check_box :private %> Private wiki
        </div>
          <% end %>
      <% end %>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/wikis/show.html.erb
<h1><%= markdown_to_html @wiki.title %></h1>
<p><%= markdown_to_html @wiki.body %></p>
  <% if policy(@wiki).edit? %>
    <%= link_to " Edit", edit_wiki_path(@wiki), id: "edit", class: 'btn btn-success glyphicon glyphicon-edit' %>
  <% end %>
  <% if policy(@wiki).destroy? %>
    <%= link_to " Delete", @wiki, method: :delete, id: 'delete', class: 'btn btn-danger glyphicon glyphicon-remove' %>
  <% end %>
<div class='row'>
  <div class="col-md-6">
    <% if current_user.role == 'admin' || current_user.role == 'premium' && current_user == @wiki.user %>
      <h3>Collaborators Added</h3>
        <table class="table table-striped">
          <%= form_for [@wiki, Collaboration.new], url: "/wikis/#{@wiki.id}/collaborators" do |f| %>
            <div class="form-group">
              <%= f.collection_select(:user_id, @users, :id, :name) %>
              <%= f.submit "Add Collaborator" %>
            </div>
          <% end %>
        <tbody>    
         <% @collaborators.each do |user|  %>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.name %><td>
            <td><%= user.email %><td>
          </tr>
       <% end %>
      </tbody>
    </table>
    <% end %>
  </div>
</div>